DROP TABLE IF EXISTS EMPLOYEE;
  
CREATE TABLE EMPLOYEE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  surname VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);


DROP TABLE IF EXISTS CLAIM;
  
CREATE TABLE CLAIM (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  code INT NOT NULL,
  name VARCHAR(250) NOT NULL,
  id_employee INT NOT NULL
  );